Repository SeeQL-Enterprises/SeeQL, pull requests merged in 2020-04, with the labels that each got.

#157 Updated Rubocop so that he can help us write better code
  .rubocop.yml
Labels: enhancement

#158 Appease Rubocop
  .rubocop.yml
  Gemfile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/collaborators_controller.rb
  app/controllers/columns_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/database_table_preferences_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/tables_controller.rb
  app/helpers/meta_tags_helper.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/collaborator.rb
  app/models/column.rb
  app/models/comment.rb
  app/models/database.rb
  app/models/project.rb
  app/models/table.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/policies/collaborator_policy.rb
  app/policies/column_policy.rb
  app/policies/comment_policy.rb
  app/policies/database_accessor_policy.rb
  app/policies/project_policy.rb
  app/policies/table_policy.rb
  app/services/database_accessor.rb
  app/services/database_processor.rb
Labels: code cleanup

#161 Who are we section
  app/assets/images/bruno.png
  app/assets/images/finn.png
  app/assets/images/patrick.png
  app/assets/images/seeql_logo_name_dark.png
  app/assets/images/tim.png
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_cards-lp.scss
  app/assets/stylesheets/components/_containers.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_who-are-we.scss
  app/views/pages/home.html.erb
Labels: enhancement, style change

#162 Bug fix footer
  Gemfile.lock
  app/assets/stylesheets/components/_footer.scss
  app/views/shared/_footer.html.erb
  package-lock.json
  package.json
  yarn.lock
Labels: bug-fix, enhancement, style change

#164 Second home button fix
  Gemfile
  Gemfile.lock
  app/views/shared/_menu.html.erb
Labels: style change

#170 My projects cards
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_flip-cards-lp.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_project-cards.scss
  app/controllers/projects_controller.rb
  app/models/project.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/projects/index.html.erb
  app/views/projects/new.html.erb
  app/views/shared/_menu.html.erb
Labels: enhancement, style change

#172 MySQL Integration
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_form.scss
  app/controllers/databases_controller.rb
  app/policies/mysql_accessor_policy.rb
  app/policies/postgres_accessor_policy.rb
  app/services/mysql_accessor.rb
  app/services/postgres_accessor.rb
  app/views/projects/_form.html.erb
  bin/rails
  bin/rake
  config/routes.rb
  db/seeds.rb
Labels: code cleanup, db:reset, enhancement, pull
